'BrauneDigital\GeoBundle\Entity\City':
    type: mappedSuperclass
    table: geo_city
    repositoryClass: 'BrauneDigital\GeoBundle\Entity\CityRepository'
    fields:
        geonameIdentifier:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: geoname_id
        latitude:
            type: float
            scale: 6
            length: null
            unique: false
            nullable: false
            precision: 9
        longitude:
            type: float
            scale: 6
            length: null
            unique: false
            nullable: false
            precision: 9
        creationDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: creation_date
        modificationDate:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: modification_date
        fcode:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        state:
            targetEntity: 'Application\BrauneDigital\GeoBundle\Entity\State'
            cascade: {  }
            fetch: LAZY
            nullable: true
            mappedBy: null
            inversedBy: null
            joinColumns:
                state_id:
                    referencedColumnName: id
            orphanRemoval: false
        country:
            targetEntity: 'Application\BrauneDigital\GeoBundle\Entity\Country'
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: cities
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
        timezone:
            targetEntity: 'Application\BrauneDigital\GeoBundle\Entity\Timezone'
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                timezone_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
