BrauneDigital\GeoBundle\Entity\CityTranslation:
    type: mappedSuperclass
    table: geo_city_translation
    fields:
        nameUtf8:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: name_utf8
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        seoDescription:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: seo_description
        seoTags:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: seo_tags
    lifecycleCallbacks: {  }
