'BrauneDigital\GeoBundle\Entity\CountryTranslation':
    type: mappedSuperclass
    table: geo_country_translation
    fields:
        name:
            type: string
            scale: 0
            length: 50
            unique: false
            nullable: false
            precision: 0
        seoDescription:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: seo_description
        seoTags:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            column: seo_tags
    lifecycleCallbacks: {  }
