'BrauneDigital\GeoBundle\Entity\StateTranslation':
    type: mappedSuperclass
    table: bd_geo_state_translation
    fields:
        nameUtf8:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: name_utf8
    lifecycleCallbacks: {  }
