parameters:
    braunedigital_geo.request.param_converter.country.class: BrauneDigital\GeoBundle\Request\ParamConverter\CountryParamConverter
    braunedigital_geo.request.param_converter.city.class: BrauneDigital\GeoBundle\Request\ParamConverter\CityParamConverter


services:
    braunedigital_geo.update:
        class: BrauneDigital\GeoBundle\Services\Update
        arguments: [@doctrine.orm.entity_manager, @service_container]

    sonata.admin.braunedigital.geo.city:
        class: BrauneDigital\GeoBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "BrauneDigital Geo", label: "Städte" }
        arguments:
            - ~
            - BrauneDigital\GeoBundle\Entity\City
            - ~
        calls:
            - [ setTranslationDomain, [BrauneDigitalGeoBundle]]
            - [ setContainer, [ @service_container ]]

    sonata.admin.braunedigital.geo.country:
        class: BrauneDigital\GeoBundle\Admin\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "BrauneDigital Geo", label: "Länder" }
        arguments:
            - ~
            - BrauneDigital\GeoBundle\Entity\Country
            - ~
        calls:
            - [ setTranslationDomain, [BrauneDigitalGeoBundle]]

    braunedigital_geo.request.param_converter.city:
        class: "%braunedigital_geo.request.param_converter.city.class%"
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: request.param_converter, converter: city, priority: 10 }

    braunedigital_geo.request.param_converter.country:
        class: "%braunedigital_geo.request.param_converter.country.class%"
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: request.param_converter, converter: country, priority: 10 }